#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
CONFIG_DIR="${REPO_ROOT}/comfy/config"
RUNTIME_CONFIG="${CONFIG_DIR}/runtime.env"
# shellcheck source=scripts/lib/config.sh
source "${SCRIPT_DIR}/lib/config.sh"
# shellcheck source=scripts/lib/comfy-cli.sh
source "${SCRIPT_DIR}/lib/comfy-cli.sh"

info() { printf '[setup] %s\n' "$*"; }
fail() { printf '[setup] ERROR: %s\n' "$*" >&2; exit 1; }

create_skeleton() {
  local directories=(
    "comfy/workflows" "comfy/config"
    "models/checkpoints" "models/diffusion_models" "models/text_encoders"
    "models/vae" "models/loras" "models/controlnet" "models/ipadapter"
    "models/clip_vision" "input" "output" "experiments" "logs" "run"
  )
  local directory
  for directory in "${directories[@]}"; do
    mkdir -p -- "${REPO_ROOT}/${directory}"
  done

  local tracked_directories=(
    "comfy/workflows" "models/checkpoints" "models/diffusion_models"
    "models/text_encoders" "models/vae" "models/loras" "models/controlnet"
    "models/ipadapter" "models/clip_vision" "input" "output"
    "experiments" "logs"
  )
  for directory in "${tracked_directories[@]}"; do
    touch -- "${REPO_ROOT}/${directory}/.gitkeep"
  done
}

write_runtime_config() {
  if [[ ! -f "${RUNTIME_CONFIG}" ]]; then
    {
      printf '# Generated by scripts/setup.sh; local absolute paths only.\n'
      printf 'COMFYUI_INSTALL_PARENT=%q\n' "${COMFYUI_INSTALL_PARENT}"
      printf 'COMFYUI_WORKSPACE=%q\n' "${COMFYUI_WORKSPACE}"
      printf 'COMFYUI_HOST=%q\n' "${COMFYUI_HOST}"
      printf 'COMFYUI_PORT=%q\n' "${COMFYUI_PORT}"
    } >"${RUNTIME_CONFIG}"
    info "Created ${RUNTIME_CONFIG}"
  else
    info "Keeping existing ${RUNTIME_CONFIG}"
  fi

}

write_model_config() {
  local output_file="${CONFIG_DIR}/extra_model_paths.yaml"
  local escaped_root
  escaped_root="$(sed 's/\\/\\\\/g; s/"/\\"/g' <<<"${REPO_ROOT}")"
  {
    printf 'editpicture:\n'
    printf '  base_path: "%s"\n' "${escaped_root}"
    printf '  checkpoints: models/checkpoints\n'
    printf '  diffusion_models: models/diffusion_models\n'
    printf '  text_encoders: models/text_encoders\n'
    printf '  clip: models/text_encoders\n'
    printf '  vae: models/vae\n'
    printf '  loras: models/loras\n'
    printf '  controlnet: models/controlnet\n'
    printf '  ipadapter: models/ipadapter\n'
    printf '  clip_vision: models/clip_vision\n'
  } >"${output_file}"
  info "Updated ${output_file} for this clone"
}

install_uv_if_needed() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  command -v brew >/dev/null 2>&1 || fail "uv is required. Install Homebrew, then run: brew install uv"
  info "uv was not found; installing it with Homebrew"
  brew install uv
  command -v uv >/dev/null 2>&1 || fail "uv installation completed but uv is not on PATH"
}

install_comfy_cli_if_needed() {
  if ! command -v comfy >/dev/null 2>&1; then
    info "comfy-cli was not found; installing it as an isolated uv tool"
    uv tool install --python 3.13 "comfy-cli>=${COMFY_CLI_MIN_VERSION}"
    export PATH="${HOME}/.local/bin:${PATH}"
    local uv_bin_dir
    uv_bin_dir="$(uv tool dir --bin 2>/dev/null || true)"
    if [[ -n "${uv_bin_dir}" ]]; then
      export PATH="${uv_bin_dir}:${PATH}"
    fi
  fi
  command -v comfy >/dev/null 2>&1 || fail "comfy-cli installed, but 'comfy' is not on PATH. Run 'uv tool update-shell', restart zsh, and rerun setup."
  local cli_error
  cli_error="$(check_comfy_cli 2>&1)" || fail "${cli_error}. Upgrade with: uv tool upgrade comfy-cli"
  info "comfy-cli capability check passed (minimum ${COMFY_CLI_MIN_VERSION})"
}

install_comfyui_if_needed() {
  local expected_workspace="${COMFYUI_INSTALL_PARENT}/ComfyUI"
  local required
  if [[ -e "${COMFYUI_WORKSPACE}" ]]; then
    for required in main.py folder_paths.py requirements.txt comfy; do
      if [[ ! -e "${COMFYUI_WORKSPACE}/${required}" ]]; then
        fail "Incomplete ComfyUI at ${COMFYUI_WORKSPACE} (missing ${required}). Move this directory aside, then rerun ./scripts/setup.sh; it will not overwrite a partial installation."
      fi
    done
    info "Existing ComfyUI detected at ${COMFYUI_WORKSPACE}; skipping installation"
    return
  fi
  [[ "${COMFYUI_WORKSPACE}" == "${expected_workspace}" ]] || \
    fail "A new comfy install creates ${expected_workspace}, but COMFYUI_WORKSPACE is ${COMFYUI_WORKSPACE}. Remove the workspace override or point it to ${expected_workspace}."
  mkdir -p -- "${COMFYUI_INSTALL_PARENT}"
  info "Installing ComfyUI for Apple Silicon at ${COMFYUI_WORKSPACE}"
  comfy --workspace="${COMFYUI_WORKSPACE}" install --m-series --fast-deps
  for required in main.py folder_paths.py requirements.txt comfy; do
    [[ -e "${COMFYUI_WORKSPACE}/${required}" ]] || \
      fail "ComfyUI installation is incomplete at ${COMFYUI_WORKSPACE} (missing ${required}). Move the directory aside and rerun setup."
  done
}

main() {
  create_skeleton
  load_editpicture_config "${REPO_ROOT}"
  normalize_comfyui_port || fail "COMFYUI_PORT must be a decimal integer from 1 through 65535"
  write_runtime_config
  write_model_config
  install_uv_if_needed
  install_comfy_cli_if_needed
  install_comfyui_if_needed

  info "Environment check passed"
  info "ComfyUI: ${COMFYUI_WORKSPACE}"
  info "Models: ${REPO_ROOT}/models (no models were downloaded)"
  if "${SCRIPT_DIR}/healthcheck.sh" >/dev/null 2>&1; then
    info "ComfyUI API is already healthy"
  else
    info "ComfyUI is installed but not running; start it with ./scripts/start.sh"
  fi
}

main "$@"
